### ISSUE TITLE
RevocationList2021 or RevocationList2021Status

### ISSUE THREAD

**Issue by kimdhamilton** [w3c/vc-status-list-2021#11]
Should the type value be `RevocationList2021Status` or `RevocationList2021` (or am I missing something?)

See:
<img width="691" alt="Screen Shot 2021-11-18 at 7 19 18 PM" src="https://user-images.githubusercontent.com/3945683/142559294-b1c59c33-ba5f-4f25-8e1e-b5e8a32f2ab6.png">

**Comment by mprorock** [comment]
StatusList2021 and StatusList2021Entry

**Comment by Sakurann** [comment]
https://w3c.github.io/vc-status-list-2021/#statuslist2021credential

**Comment by mprorock** [comment]
> StatusList2021 and StatusList2021Entry

I would strongly request StatusList and StatusListEntry

**Comment by mprorock** [comment]
if we need a ver embedded in there...
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "id": "https://example.com/credentials/status/3",
  "type": ["VerifiableCredential", "StatusListCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:40Z",
  "credentialSubject": {
    "id": "https://example.com/status/3#list",
    "type": "StatusList",
    "ver": "2.0",
    "statusPurpose": "revocation",
    "encodedList": "H4sIAAAAAAAAA-3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAIC3AYbSVKsAQAAA"
  },
  "proof": { ... }
}
```

**Comment by Sakurann** [comment]
we can continue the conversation in Issue #50

**Comment by msporny** [comment]
> I would strongly request StatusList and StatusListEntry

Very strong -1 to this, it would paint us into a corner so that we wouldn't be able to make breaking changes in the future.

**Comment by brentzundel** [comment]
This issue has been somewhat overtaken by events.
The group has settled on `StatusList2021Entry` as the type.

Closing this issue.
If folks want something other than `StatusList2021Entry` please open a new issue.

**Comment by Sakurann** [comment]
> Very strong -1 to this, not versioning would paint us into a corner so that we wouldn't be able to make breaking changes in the future.

@msporny I am not suggesting not to version ;) just hoping we can find a way to version without using years :)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-31-vcwg-special#section2-5) on 2023-01-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5.  (issue vc-status-list-2021#11)

_See github issue [vc-status-list-2021#11](https://github.com/w3c/vc-status-list-2021/issues/11)._




**Brent Zundel:** what should the type value be.  
… I think this is stale / old and has been fixed..  

**Manu Sporny:** this is about old langauge that no longer exists.  
… seems we should close this issue, and note that we have changed the name.  

**Kristina Yasuda:** +1 to the direction, curious.... why is there a 2021 in the name, can we drop it?.  

> *Michael Jones:* Please delete the 2021.

**Manu Sporny:** yeah, typically we version things... and we like to be able to tell versions apart.  

> *Shawn Butterfield:* Can we use SemVer then?.

**Manu Sporny:** dates have been used fro crypto suites, so you can tell how old something is.  

> *Michael Prorock:* +1 shawn.

**Manu Sporny:** we you see v1, v2, v3... you have no sense of time.  

> *Orie Steele:* whereas dates tell you something about time.

> *Michael Prorock:* but is json, why just not add semver as a property in the json.

**Manu Sporny:** first question, do we want versioning? yes... do we want semantic versioning or date based versioning.  
… we do stuff differently all over the place.  
… dates are in names when time is important.  
… I will note that this has paid off well.  
… because if we had not versioned we would have been stuck with RSA suites forever.  

**Kristina Yasuda:** first question is what are we trying to version.  

> *Michael Prorock:* [https://github.com/w3c/vc-status-list-2021/issues/11#issuecomment-1411229291](https://github.com/w3c/vc-status-list-2021/issues/11#issuecomment-1411229291).

**Kristina Yasuda:** we should version specs based on publication date maybe.  
… lets agree on what we are trying to version, and then discuss how to do it.  
… I would be in favor of dropping date versioning.  

> *Michael Prorock:* dates typically imply bias (newer is better).

> *Kristina Yasuda:* I think cryptosuites versioning is different.

> *Michael Prorock:* or as it ages....

**Orie Steele:** I also was surprised to learn about this long history of adding dates to specs to version them and recently in Chairing capacity came across IDNA2003 and IDNA2008 and UTS46 and it has rekindled my deep appreciation that people have always struggled on clean versioning schemes. It does seem to me that putting a date on things was more popular in the past then it is today, W3C community is last holdout to put dates on things and others have.  

> *Manu Sporny:* moved on from this practice since then. Maybe an older convention and not current best practice. There are things out there that people are referring to and arguing over and fact that it has 2008 causes people to argue over it more than if it didn't..

**Manu Sporny:** I would not say its an old thing.  
… it was easy for us to just use dates, thats why we picked them.  
… people don't try to find new versions.  
… kristina asked, what are we trying to version... we are trying to version the "object".  
… not the spec.  
… if we had started off without adding a version to the RDF type, we would have been trapped.  
… now we can add new RDF classes for each new type we create, so we can tell the RDF types apart.  
… people have strong opinion on this, feels like a rat hole.  

> *Brent Zundel:* Is StatusList2021 worse than StatusListV1 ?.

> *Kristina Yasuda:* filed an issue: [https://github.com/w3c/vc-status-list-2021/issues/50](https://github.com/w3c/vc-status-list-2021/issues/50).

> *Dmitri Zagidulin:* @brentz: that was my question too.

**Brent Zundel:** regarding this particular issue, feels like we can close it.  

> *Shawn Butterfield:* +1 close it.

**Brent Zundel:** any objection?.  

**dimitry:** I was going to ask what you asked in chat.  

> *Kristina Yasuda:* +1 to StatusListV1.

> *Orie Steele:* is StatusListV1 better or worse than StatusList2023.

**Brent Zundel:** closing this issue.  

> *Dmitri Zagidulin:* thaaanks Orie!.

> *Shawn Butterfield:* thanks, Orie :high-five:.

> *Phil ASU:* + putting a year in the status list ends of causing questions when there haven't been changes as people think i's moribund, not simply still doing strong. ;-).

---

</details>
