### ISSUE TITLE
Context about how this differs from 2020-rl

### ISSUE THREAD

**Issue by swcurran** [w3c/vc-status-list-2021#3]
It would be very helpful if the specification referenced the vc-revocation-list-2020 and defined the differences between the two. I've been trying to scan to figure out the differences, and from what I can see a couple of mentions (and an example) of "SuspensionList" is the only change.  Is that correct?

A related question is whether the VC for the list have a type that MUST be "RevocationList2021" as stated, or would it also allow "SuspensionList2021" to align with the addition of allowing SuspensionList in the VC given to the holder?

If that is the case, I would add my name to the question in #2 asking why not add a "call it whatever you want" `listtype` field so you aren't limited to revoke and suspend.

Thanks!

**Comment by csuwildcat** [comment]
This is the direction I would hope to go - just allow a field like `topic` where the status topic can be whatever the list implementer wants (possibly with a registry of known values and their meanings).

**Comment by csuwildcat** [comment]
@msporny as we begin implementing this in our production stuff, we would really like to see the concept of topic/list-type. This is important because what we really want is to have all the lists be `StatusList2021`, but have that status topic be different depending on the need/goal. The concept of a topic/list-type would make that easier, imo.

**Comment by kezike** [comment]
Agreed with the points here, especially considering that there is seemingly no material difference between `SuspensionList2021` and `RevocationList2021` in the current version of this spec.

**Comment by msporny** [comment]
> This is the direction I would hope to go - just allow a field like `topic` where the status topic can be whatever the list implementer wants (possibly with a registry of known values and their meanings).

Feels reasonable, especially since we don't have a test suite for interop yet... we'd want to get this locked in before one is created. I'm trying to think through how the change might blow up in our faces... I haven't had a chance to think deeply about that so would prefer some implementer feedback before we commit to the new design path.

The old design clearly specifies the type in both the VC that points to the status list, and the status list itself (so there can be no confusion on what the list is for). If we were to do this, there would be an extra type check required to make sure the topics line up... if we don't do that, there could be an attack where you swap a suspension list for a revocation list (maybe?!)... I don't know, but someone needs to think about the attacks around this deeply before we implement it. Has anyone thought through how one would attack a topic mismatch?

**Comment by sbutterfield** [comment]
@msporny 
Currently going through an implementation cycle of this myself, I have some thoughts:

> A related question is whether the VC for the list have a type that MUST be "RevocationList2021" as stated, or would it also allow "SuspensionList2021" to align with the addition of allowing SuspensionList in the VC given to the holder?

I had planned on publishing separate Status List VCs, one for Suspension List, one for Revocation List, that's how I interpreted it anyway, and then each VC had a service reference back to its applicable Status List VC target resource. This way a VC could be revocable and/or suspendable in credential definition spec by the issuer. 

> especially considering that there is seemingly no material difference between SuspensionList2021 and RevocationList2021 in the current version of this spec.

I had looked at this a bit differently in implementation. Here were the rules intended for issuing parties:
1. Suspended credentials can be un-suspended
2. Revoked credentials can never be un-revoked... only re-issued

This ruleset implies the need for two separate bitstrings and two separate list types identifying those bitstrings, right? 

> if we don't do that, there could be an attack where you swap a suspension list for a revocation list (maybe?!)
If type is part of the digest for the Status List VC, then it should be impossible to override the verification of a Revocation List with a verification of the Suspension List, no?

**Comment by msporny** [comment]
> If type is part of the digest for the Status List VC, then it should be impossible to override the verification of a Revocation List with a verification of the Suspension List, no?

Yes, exactly. +1 to everything you said above. There are at least two different types of status lists today (revocation and suspension, with dangerous ramifications wrt. mixing up one w/ the other).

We could further generalize this like we plan to do in the upcoming Data Integrity work (namely, by reusing something akin to the `cryptosuite` property):

https://w3c-ccg.github.io/data-integrity-spec/#example-a-dataintegritysignature-example-using-a-nist-ecdsa-2022-cryptosuite

So, another alternative might be:

```
  "credentialStatus": {
    "id": "https://dmv.example.gov/credentials/status/3#94567",
    "type": "StatusList",
    "statusType": "revocation-2021", <--- this would be a string, not a JSON-LD type
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  }
```

... and the list would look like this:

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc-status-list-2021/v1"
  ],
  "id": "https://example.com/credentials/status/3",
  "type": ["VerifiableCredential", "StatusListCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:40Z",
  "credentialSubject": {
    "id": "https://example.com/status/3#list",
    "type": "StatusList",
    "statusType": "revocation-2021", <--- this would be a string, not a JSON-LD type
    "encodedList": "H4sIAAAAAAAAA-3BMQEAAADCoPVPbQwfoAAAAAAAAAAAAAAAAAAAAIC3AYbSVKsAQAAA"
  },
  "proof": { ... }
}
```

Food for thought...

**Comment by csuwildcat** [comment]
Just to throw this out there: our whole desire with Status List was to have
a generic descriptor/model that featured the exact list-typing field you
suggested, not whole separate specs for N-types of lists. I'm not sure why
that wasn't something folks were into previously, but I would certainly be
happy to see it move that direction if it's more palatable now.

**Comment by sbutterfield** [comment]
@msporny, +1 very much like the idea for a type to refer to a data integrity signature that itself is verifiable.

A challenge presented in our desired implementation: 
-- `credentialStatus: {}` is currently specified as an object. How would we expect a verification agent to reconcile a credential that could be either revoked or suspended? Is there a semantic elsewhere in DID Core that allows for an array representation of status' on a VC?

**Comment by msporny** [comment]
> How would we expect a verification agent to reconcile a credential that could be either revoked or suspended? Is there a semantic elsewhere in DID Core that allows for an array representation of status' on a VC?

Your answer is in the VC Data Model spec, namely, this line:

https://www.w3.org/TR/vc-data-model/#syntaxes -- "All other properties, if present, are represented as either a single value or an array of values."

So, the value associated with `credentialStatus` can be an array, and if you have a credential that could be either revoked or suspended, do this (eventually, per the suggestion above):

```
  "credentialStatus": [{
    "id": "https://dmv.example.gov/credentials/status/3#94567",
    "type": "StatusList",
    "statusType": "revocation-2021",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  }, {
    "id": "https://dmv.example.gov/credentials/status/4#82930",
    "type": "StatusList",
    "statusType": "suspension-2021",
    "statusListIndex": "82930",
    "statusListCredential": "https://example.com/credentials/status/4"
  }]
```

It's going to end up being some variation of the example above once we get consensus on what the community wants to do here.

**Comment by sbutterfield** [comment]
@msporny Ha! Right there under "Syntactic Sugar"

> This section describes some of these approaches, which will likely go unnoticed by most developers, but whose details will be of interest to implementers

😏 
Thank you

**Comment by dlongley** [comment]
I think we can simplify `statusType` values to: `"statusType": "revoked"`, `"statusType": "suspended"` (and anything else we want). I don't think we need to use `revocation-2021` values, etc. It also feels more natural given the binary state here, i.e., "revoked" is either set or not / true or false, as opposed to `revocation-2021` is set or not / true or false.

The value space is just a string so we can always, if need be, get more complicated in the future, but let's start with simple values and chances are we won't need a more complicated future.

**Comment by msporny** [comment]
> `"statusType": "revoked"`, `"statusType": "suspended"`

I'm concerned that a developer might check that field, not read the spec (gasp), or try to understand how any of this works (double gasp), and presume the credential is revoked and/or suspended. :(

I'm also uncertain about removing a date stamp entirely from the status suite.

Food for thought.

**Comment by sbutterfield** [comment]
@dlongley, (forgive the uninformed inquiry) does json-ld provide no modality for something like a `status` or `type` to be situationally interpretable depending on the context in which it's used? 

Seems to me, as an implementor anyways, that I'd want to allow a derived status type if required. `revoked/suspended/inactive/unpaid/in-default/under-review` are all contextually relevant types that a binary response can answer. Thus, as long as a spec provides a controlled algorithm for providing the binary response, and requires the document's generator to provide the context to the ecosystem interpreting it (often familiar with DSL of the type anyways), then couldn't that provide a better implementation pattern? 

I'm admittedly still coming up to speed so forgive any sweeping assumptions.

**Comment by dlongley** [comment]
@sbutterfield,

> @dlongley, (forgive the uninformed inquiry) does json-ld provide no modality for something like a status or type to be situationally interpretable depending on the context in which it's used?
> 
> Seems to me, as an implementor anyways, that I'd want to allow a derived status type if required. revoked/suspended/inactive/unpaid/in-default/under-review are all contextually relevant types that a binary response can answer. Thus, as long as a spec provides a controlled algorithm for providing the binary response, and requires the document's generator to provide the context to the ecosystem interpreting it (often familiar with DSL of the type anyways), then couldn't that provide a better implementation pattern?

So, with JSON-LD / RDF, you can make the semantics for a vocabulary term whatever you want in the text that defines it. What we're doing by using `statusType` and having it hold a string value is removing the requirement that authors must create new JSON-LD vocabularies and contexts and update implementations to install and use them whenever there is a need for a new status type string.

Instead, status types can be independently described in specs or along with the definitions provided for particular credential types and / or issuers. The verification software that needs to be able to report whether or not a particular status is set can then be separated from the business rules for evaluating what to do about a particular status in a given context -- which I think fits along with what you'd like to see here as well.

**Comment by sbutterfield** [comment]
@dlongley 
Yep, I'm picking up what you're throwing down. There's a delicate balance there I didn't fully consider. 

@msporny

> I'm concerned that a developer might check that field, not read the spec (gasp), or try to understand how any of this works (double gasp), and presume the credential is revoked and/or suspended

I've seen some pretty bad design assumptions in my day (heck, I just made one) ... just my thoughts after reading both of your remarks:
1. `statusType` should be harder to confuse in practice to a heedless dev 
2. `statusType`  could be readable sans YYYY designation if its value is interpreted to be "for the purposes of" ... ie: instead of `revoked` as proposed or `revocation-2021`, use `revocation`. Instead of `suspended` use `suspension`, for example. Maybe instead of `statusType` it is `statusPurpose` or just `purpose`. 
I dunno 🤷🏻 , but I can see why this is such a hard thing to agree upon.

**Comment by msporny** [comment]
> 2\. `statusType`  could be readable sans YYYY designation if its value is interpreted to be "for the purposes of" ... ie: instead of `revoked` as proposed or `revocation-2021`, use `revocation`. Instead of `suspended` use `suspension`, for example. 

Yes, exactly this. @dlongley thoughts?

> Maybe instead of `statusType` it is `statusPurpose` or just `purpose`.

Just "purpose" is a bit challenging because we try to use terms that are difficult to confuse outside of their used context. That is, the word purpose, used in other contexts, can mean different things. For example "proofPurpose", which is a real thing: https://w3c-ccg.github.io/security-vocab/#proofPurpose

We /could/ define one generic meaning for "purpose" that is used across all security contexts, but things have usually backfired when we've tried that in the past. That's not a hard and fast rule, though... we do have `id` and `type` and those are shared across ALL of JSON-LD to mean something very specific. We do also have `[challenge](https://w3c-ccg.github.io/security-vocab/#challenge)` and `[domain](https://w3c-ccg.github.io/security-vocab/#domain)`... so, again, we've broken this general guidance before (in the early days... as in, nearly a decade or so ago).

At present, I think I'm leaning more towards `statusSOMETHING`... I find `statusPurpose` compelling, will need to think about it over the next week to see if any "shower/dishwashing thoughts" pop up.

>     I dunno 🤷🏻 , but I can see why this is such a hard thing to agree upon.

There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors. -- [Leon Bambrick](https://martinfowler.com/bliki/TwoHardThings.html) :P

**Comment by msporny** [comment]
A PR has been raised to address this issue. @sbutterfield check out PR #24. All PRs in this repo (and most W3C repos) come w/ a "Preview" link in the initial PR comment. See this link for latest PR Preview: https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-status-list-2021/pull/24.html

**Comment by dlongley** [comment]
+1 to `statusPurpose`.

**Comment by Sakurann** [comment]
PR merged. is this ready to be closed?

**Comment by msporny** [comment]
> PR merged. is this ready to be closed?

The initial request asked to compare/contrast this spec against the Revocation List 2020 spec. Given that we plan to EOL Revocation List 2020 and that most implementers are moving to StatusList2021, I'm going to assert that we just not say anything about the old spec in the new spec, put a "this spec replaced by StatusList2021" on the old spec, and never talk about the old spec again. :)

The other part of the initial request was to add `statusPurpose`, which was done in PR #24. 

I believe this addresses the initial request, so closing this issue. Re-open if you disagree, @swcurran.
