### ISSUE TITLE
Define TTL and caching behavior for lists

### ISSUE THREAD

**Issue by OR13** [w3c/vc-status-list-2021#38]
This applies to the list that must be dereferenced.

The object that is dereferenced should be held in cache for the duration, this would enable more power efficient (less energy wasteful) credentials.

Every network request costs power.

**Comment by Sakurann** [comment]
isn't that up to the verifier's policy? how often to cache?

**Comment by OR13** [comment]
I'm fine with the TTL in the object, and not in HTTP headers.

**Comment by dlongley** [comment]
We should recommend people use `validFrom` and `validUntil` in the status list VC.

**Comment by longpd** [comment]
Agreed that it needs to be in the object. Re: Sakurann's question, I don't think this is a business policy. It's more a security concern

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-24-vcwg-special#section1-2) on 2023-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Define TTL and caching behavior for lists (issue vc-status-list-2021#38)

_See github issue [vc-status-list-2021#38](https://github.com/w3c/vc-status-list-2021/issues/38)._




**Kristina Yasuda:** Going to the next issue, 38.  
… Should we discuss this or move on?.  

**Orie Steele:** I can provide some verbal update.  
… This also applies to the behavior of the object that is dereferenced.  
… Imagine you get that list, how long should you hold on to it before you refresh?.  

**Manu Sporny:** time to live can be expressed in many ways, in HTTP headers or the object itself.  
… I think we should put it in the object itself.  
… The statuslist is signed by the issuer, so the holder can deliver that list to the verifier.  
… as a more privacy preserving way to do it, especially for offline scenarios.  

> *Dave Longley:* +1 to Manu.

**Manu Sporny:** So there's an argument for putting in the object itself so its clear no matter the delivery mechanism.  

> *Dave Longley:* +1 to just use validUntil and validFrom.

**Manu Sporny:** We could do both, but that seems like a bad idea. The real time-to-live should be in the object, which might be echoed in the header.  

**Dave Longley:** since the status list itself is a VC itself, we should recommend we just use those.  

> *Manu Sporny:* +1 to reuse validFrom / validUntil.

> *Andres Uribe:* +1 to reusing.

**Kristina Yasuda:** looks like we need more discussion? Or is it straightforward..  

**Manu Sporny:** could be ready for PR, if all we are doing is using validFrom/validUntil.  
… So ready for PR, I imagine.  

**Kristina Yasuda:** ok, I don't see any objections to that.  

</details>

**Comment by OR13** [comment]
I think this can be closed
