### ISSUE TITLE
Verification should fail for revocable credentials for status list that cannot be deferenced

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c/vc-status-list-2021#39]
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  // if this 404 the credential should fail to verify
  "id": "https://example.com/credentials/23894672394",
  "type": ["VerifiableCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:42Z",
  "credentialStatus": {
    // if this 404 the credential should fail to verify
    "id": "https://example.com/credentials/status/3#94567",
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  },
  "credentialSubject": {
    "id": "did:example:6789",
    "type": "Person"
  },
  "proof": { ... }
}
```

**Comment by dlongley** [comment]
The spec should definitely say something about what to do if the status list credential cannot be retrieved.

**Comment by OR13** [comment]
I edited to make it clear that we are not providing sufficient guidance on `credential.id` and `credentialStatus.id`

**Comment by OR13** [comment]
This issue is not about "validation" it is about "verification"... I believe the behavior is not sufficiently defined to be safely used during "verification".

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-24-vcwg-special#section1-1) on 2023-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.1. Verification should fail for revocable credentials for status list that cannot be deferenced (issue vc-status-list-2021#39)

_See github issue [vc-status-list-2021#39](https://github.com/w3c/vc-status-list-2021/issues/39)._




**Kristina Yasuda:** There are no comments. Just an example.  
… So what do we do if the URL is a bad one?.  

**Manu Sporny:** there's a difference between verification and validation.  
… verification is checking signatures... validation is different.  
… Some verifiers might not care if the credential is suspended or revoked.  
… So I think this is about validation not verification.  
… We should provide some guidance about this.  
… Probably in the StatusList spec, not the VCDM spec.  
… If that sounds right, we could mark Ready for PR.  
… But haven't had a chance to discuss yet..  

> *Andres Uribe:* Just a note - verification is defined in the spec as including that "... if present, the status check succeeds".

> *Manu Sporny:* yes, andres, good point....

**Kristina Yasuda:** so you're saying if a verifier doesn't care, ignore the 404, if they do, it should fail..  

**Orie Steele:** it's concerning that a verifier might not care.  

> *Dave Longley:* +1 to something along the lines of what Kristina said ... if the verifier cares about status and can't retrieve the status list credential, it should result in a validation failure.

**Orie Steele:** the status and id are two URLs that we need to define what they dereference to.  

> *Manu Sporny:* ^ yes, +1 to that..

**Orie Steele:** and what happens if they fail.  

> *Manu Sporny:* (to what dlongley said).

**Joe Andrieu:** This may have been a scribe error, but what I heard in your summary, Kristina, was about Verification, but what Manu noted was it's about "Validation". Orie is saying it should be a part of Verification, but Manu is saying, because it is a part of business rules, it's a part of Validation..  

**Kristina Yasuda:** I think we agree this isn't about validation. It's about business rules?.  

> *Dave Longley:* "validity of the credential" is "business logic" (as opposed to verification) ... at least that's how we've talked about it in this group in the past..

**Manu Sporny:** I'm nitpicking on some of the language.  
… it's not about business rules, it's about validation. But validation *is* about business rules..  
… Some of us are saying this is validation, which is where additional rules kick in..  

> *Ted Thibodeau Jr.:* +1 validation is about business rules, which may care about verification results *including* failures.

**Manu Sporny:** Andres pointed out something interesting. If present, the status check needs to succeed, and it's not clear what that means.  
… Need to clarify validation is about running a set of business rules.  
… And if the use case needs to vary based on status, that happens in validation.  

**Kerri Lemoie:** are we sure its validation?.  
… I thought verification is from what's in the space and validation is business rules.  

> *Manu Sporny:* It's a good question, Kerri..

**Kerri Lemoie:** So, fit for role is a business rule, but the status is verification.  

> *Dave Longley:* our definition from the spec today: [https://www.w3.org/TR/vc-data-model/#dfn-verify](https://www.w3.org/TR/vc-data-model/#dfn-verify) (not that it couldn't change).

**Kristina Yasuda:** I think both are happening..  
… making sure there is a valid URL and checking it is "verification" and making a decision based on that is "validation".  

**Orie Steele:** This issue is filed specifically for verification. We filed it..  
… If verifying is inconsistent, that leads to problems..  
… Which will lead to different behaviors by different verifiers.  
… If folks want to layer validation in front, that's fine. But this is a security issue about verification.  

> *Kerri Lemoie:* Reference we've been using for verification & validation: [https://github.com/w3c-ccg/vc-api/blob/main/verification.md](https://github.com/w3c-ccg/vc-api/blob/main/verification.md).

**Orie Steele:** about verifying a credential that is revocable.  

**David Waite:** Like a lot of things this is a condition of use that the issuer is setting.  
… I think this should be in the main spec the same way that a verifier that accepts expired credentials... it may be a business decision but it still matters.  

**Manu Sporny:** The [current spec states](https://www.w3.org/TR/vc-data-model/#status-0) (see link). Status checking is a part of validation..  
… However, I agree that it is important that everyone does it the same way..  
… Where to put the language is a fair question.  
… We might be able to waive our hands around what "must succeed" means.  
… But I'm not sure how to do it, because if we have it in two places, we start to have validation creep into the VCDM.  
… Hard decision either way. Status checking is part of validation. We don't say anything about it in current VCDM.  
… Not sure what language would solve the problem.  

**Brent Zundel:** I think there's a clear separation between validation and verification.  

> *Orie Steele:* +1 Brent, its not possible to "verify" a revocable credential, unless this is defined properly..

**Brent Zundel:** You can't verify unless you can get the response from status list endpoint.  

> *Manu Sporny:* +1 brent, that feels workable..

> *Kerri Lemoie:* Would any spec outside of VC but used as part of VC be considered validation instead of verification?.

**Brent Zundel:** So we can say the status property must provide information..  

> *Dave Longley:* +1 to brent.

**Brent Zundel:** Whether the verifier does anything with that information, is a validation choice.  

> *Andres Uribe:* +1 to that.

**Gregory Natran:** We have to cover some of the basic security and processing..  
… but if we get different credential rules about what is usable here or there, that models the real world.  

**Orie Steele:** I'm confused by the comments about validation v verification.  
… can I get clarity about whether or not the expiry date impacts verification.  
… Whatever we say about validity date. That same sentence should be applied to this format.  
… It's the intention of the issuer to communicate something essentially the same.  

> *Andres Uribe:* both verification and validation are clearly defined in the vc-data-model spec.

**Kristina Yasuda:** it looks like we need a new issue to talk about verification and validation.  

**Brent Zundel:** I think the division is the same in both cases..  
… If there is a validFrom date, if that's there it needs to be a valid date.  
… The verifier should check that.  
… but if the verifier cares about that date is validation.  

> *Orie Steele:* So "issuanceDate" and "credentialStatus" are equally the responsibility of the verifiers "validation process" ?.

**Manu Sporny:** what Brent said. That's a philosophy we can apply to all of these..  
… namely that it has to be syntactically valid.  
… So the ID has to be a URL and we could add has to be dereferenceable and must get data back from it.  

> *Orie Steele:* I think it "has to dereference to an object of the type noted by the list"... or it does not work..

**Manu Sporny:** Then, once you get into processing, that will be highly dependent on the type of Status List it is.  

> *Orie Steele:* also the thing that is "dereferenced" needs to be verified.....

**Manu Sporny:** Do we want to say something about the status check has to pass?.  
… We do already say that in a validation section and status section.  

> *Orie Steele:* +1 Manu, we do need to describe what the verifier does with the object that is dereferenced..

> *Orie Steele:* or verifiers will handle it differently..

**Manu Sporny:** If the property is available, it is expected to be evaluated by the verifier.  

> *Dave Longley:* it has to be possible for the verifier to do the evaluation.

> *Kristina Yasuda:* q.

> *Phillip Long:* +1 to Manu's suggestion..

> *Manu Sporny:* I will try to write something that makes sense, then :P.

**Kristina Yasuda:** looks like it is ready for PR for the beginning language. We can play with it once the PR is filed.  

> *Manu Sporny:* I think I have enough to go on..

</details>

**Comment by morgatron** [comment]
This is a great discussion!
I realise I've missed parts of it and it's still ongoing., but it's not clear to me whether after this discussion the title of this issue holds true? (And I'd really like to know whether it does!  :smile:  )

**Comment by msporny** [comment]
Looking at the request in the initial issue more closely...

@BenjaminMoe wrote:
```
  // if credential.id 404s, the credential should fail to verify
  "id": "https://example.com/credentials/23894672394",
```

No, there is no requirement that you should be able to dereference the ID for the VC. There are at least two use cases where if we require dereferencing for this value, it'll break the ecosystem:

1. You might not have authorization to access the VC, but that doesn't mean the VC you're verifying/validating is invalid (if you can properly check the digital proofs on the VC).
2. This value can be a non-dereferenceable ID, such as `urn:uuid:cbf04a28-a000-11ed-8b71-3b506da91aa0`, and that doesn't mean the VC you're verifying/validating is invalid (if you can properly check the digital proofs on the VC).

-1 to adding the "should fail to verify" language as it'll unnecessarily break deployed systems.

@BenjaminMoe wrote:
```
  "credentialStatus": {
    // if credentialStatus.id 404s the credential should fail to verify
    "id": "https://example.com/credentials/status/3#94567",
```

Again, this value isn't depended upon during validation/verification and can be any URL (dereferenceable or not). Like the above, it can be a URL to a resource you don't have authorization to access, or it can be a non-dereferenceable URL such as a UUID.

-1 to adding "should fail to verify" language as it unnecessarily constrains deployments.

All that to say, `credential.id` and `credentialStatus.id` are optional fields and aren't used during the verification or validation process.

That said, we DO want to say something about `credentialStatus.statusListCredential` ... if you care about credentialStatus and can't dereference that, validation should fail. We currently do say this:

> The statusListCredential property MUST be a URL to a [verifiable credential](https://w3c.github.io/vc-status-list-2021/#dfn-verifiable-credentials). When the URL is dereferenced, the resulting [verifiable credential](https://w3c.github.io/vc-status-list-2021/#dfn-verifiable-credentials) MUST have type property that includes the StatusList2021Credential value.

So, not being able to dereference the URL to an object that has a type property of `StatusList2021Credential` will clearly result in an error (per the spec). I'll put together a PR that makes this more explicit.

**Comment by msporny** [comment]
PR #46 has been raised to address this issue. Once PR #46 has been merged, this issue will be closed.
