### ISSUE TITLE
Bitstring endianness

### ISSUE THREAD

**Issue by clehner** [w3c/vc-status-list-2021#8]
The endianness of the bitstring should be specified.

i.e. Does index "0" of the bitstring refer to the leftmost bit in the first byte (bit mask `0x80`) or to the rightmost bit of the first byte (bit mask `0x01`)

**Comment by dlongley** [comment]
IIRC, current implementations use little endian (index of `0` refers to the leftmost bit) and +1 to making this clear in the spec and including diagrams.

**Comment by dlongley** [comment]
Hmm, no, just checked and looks like current implementations use big endian (index of `0` refers to the right most bit in the first byte (`0x01`). We will want to get this cleared up and make a choice.

**Comment by dlongley** [comment]
We've updated our implementations to ensure that both the bit order and the byte order are consistently little endian. We should specify this in the spec and fix any examples that might suggest otherwise.

**Comment by dlongley** [comment]
See issue #36.

**Comment by OR13** [comment]
suggest closing as a dupe after #36

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-01-24-vcwg-special#section1-7) on 2023-01-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.7.  (issue vc-status-list-2021#8)

_See github issue [vc-status-list-2021#8](https://github.com/w3c/vc-status-list-2021/issues/8)._




**Kristina Yasuda:** Issue 8.  
… Looks like debates about issue..  

> *Dave Longley:* this is a duplicate.

**Manu Sporny:** This looks like a dupe.  

**Kristina Yasuda:** Ok, we'll close it as a dup.  
… Thanks everyone. That was a productive discussion.  
… Looking forward to reviewing PRs in main call.  
… See you all tomorrow at the same time.  

---

</details>
